version: "3.1"
services:
  database:
    image: mariadb:10.5
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/

    environment:
      - "MYSQL_ROOT_PASSWORD=iamgroot"
      - "MYSQL_DATABASE=crm"